---
- name: Hello World!
  hosts: localhost
  become: true
  remote_user: admin
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
 
  - name: Hello World!
    shell: echo "Hi! Tower is working."
