---
- hosts: minikube
  become: yes
  gather_facts: false
 

  tasks:
  - name: add tomcat group
    group:
      name: tomcat

  - name: add tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /user/share/tomcat
      createhome: no
